### ISSUE TITLE
CODE RUNNING ISSUE

### ISSUE THREAD

**Issue by SAHILKUMAR97** [RealVNF/DeepCoord#3]
SIR, CONGRATULATIONS ON YOUR WORK.
SIR, I FOLLOW YOUR README TO RUN THE CODE BUT GOT AN ISSUE WHEN TRYING TO RUN THIS CODE.
1) tensorboard  --logdir==./graph, when I got the link and try to run that link then it throws an error like - NO dashboard is active for the current dataset.
PROBLEM CAUSES: 1) YOU HAVE NOT WRITTEN ANY DATA TO YOUR EVENT FILES
                                  2) TENSORBOARD CAN'T FIND YOUR EVENT FILES.
2) WHEN I TRY TO RUN eval_example.ipynb then it gives KEY ERROR -'NETWORK'

**Comment by stefanbschneider** [comment]
Thanks @SAHILKUMAR97 

I think both of your issues are because you have not run DeepCoord up front, right?

You can't view TensorBoard requires the `graph` dir, which is created automatically, when you run DeepCoord.

Similarly, the evaluation notebook was just an example to analyze results *after* running DeepCoord.

---

To help getting started with DeepCoord, I removed the old evaluation notebook and instead created a new tutorial/quick start notebook here: https://github.com/RealVNF/DeepCoord/blob/master/quickstart.ipynb

You can also look at it and run it in Google CoLab: https://colab.research.google.com/github/RealVNF/DeepCoord/blob/master/quickstart.ipynb

I hop this helps?

**Comment by SAHILKUMAR97** [comment]
Sir why you are not using DEEP Q LEARNING ALGO?
I AM USING THIS BUT NOTHING HAPPENS?

**Comment by stefanbschneider** [comment]
@SAHILKUMAR97 Deep Q-Learning is for discrete actions, but here we need continuous actions. That's why we use DDPG. An alternative would be SAC or PPO, for example.

What do you mean with "nothing happens"? What are you running and what is the output? Did you check out the quick start notebook?
https://github.com/RealVNF/DeepCoord/blob/master/quickstart.ipynb

**Comment by SAHILKUMAR97** [comment]
Sir, when I am running your code I got this error.When I am trying to run
this command
: pip Install -r requirements.txt

**Comment by stefanbschneider** [comment]
Which error?

**Comment by SAHILKUMAR97** [comment]
Sir my terminal got stuck at this point, what can I do?

**Comment by SAHILKUMAR97** [comment]
Thanku so much sir and sorry to disturb you.
Finally I am able to get what I want from your code. Sir pls advice me how
to use PPO on this so that I can get better idea.

**Comment by stefanbschneider** [comment]
If you just want to use DeepCoord, you can use it out of the box, i.e., with DDPG - it should work quite well.

If you want to switch to another algorithm, eg, PPO, you'll have to change corresponding DDPG agent class: https://github.com/RealVNF/DeepCoord/blob/master/src/rlsp/agents/rlsp_ddpg.py#L101
Or, better, create a new PPO agent class inheriting from the super class: https://github.com/RealVNF/DeepCoord/blob/master/src/rlsp/agents/rlsp_agent.py

Since DeepCoord currently builds on keras-rl, which is more or less discontinued, you'll have switch to another RL framework (eg, stable baselines) or implement PPO yourself. So, it's quite a lot of effort and I'd advise to first get started with DeepCoord as it currently is (with DDPG) before trying to customize it.

**Comment by SAHILKUMAR97** [comment]
Thanks, I'll check it out. Sir you are using abelian network as data set.

**Comment by SAHILKUMAR97** [comment]
Sir, which dataset are you using for training and testing purpose?

**Comment by stefanbschneider** [comment]
In the DeepCoord paper, we used many different parameters to evaluate the approach. You can find the paper [here](https://ieeexplore.ieee.org/document/9419067) ([preprint](https://ris.uni-paderborn.de/download/21808/21809/ris-accepted-version.pdf)).

Most of the parameters are here: https://github.com/RealVNF/DeepCoord/tree/master/res

For example, you can run DeepCoord on the Abilene network with 1 ingress node and random capacities, a service with 3 components, and stochastic flow arrival using these parameters:

* https://github.com/RealVNF/DeepCoord/blob/master/res/networks/abilene/abilene-in1-rand-cap.graphml
* https://github.com/RealVNF/DeepCoord/blob/master/res/service_functions/abc.yaml
* https://github.com/RealVNF/DeepCoord/blob/master/res/config/agent/ddpg/agent_obs1_only-flow_64a_64c_099gam_00001tau_001alp_0001dec.yaml
* https://github.com/RealVNF/DeepCoord/blob/master/res/config/simulator/rand-arrival10_det-size001_duration100.yaml

Or for a simple test, use the parameters from the readme.

**Comment by SAHILKUMAR97** [comment]
Awesome, thanks!
